from __future__ import annotations

from typing import Any, Protocol

from .models import MemoryItem, MemoryQuery, MemorySearchResult, UpsertOutcome


class MemoryStore(Protocol):
    def upsert(self, item: MemoryItem) -> UpsertOutcome: ...

    def get(self, memory_id: str) -> MemoryItem | None: ...

    def search(self, query: MemoryQuery) -> list[MemorySearchResult]: ...

    def delete(self, memory_id: str, *, reason: str) -> bool: ...

    def set_status(self, memory_id: str, status: str, *, reason: str) -> bool: ...

    def resolve_conflict(self, winner_id: str, *, reason: str) -> int: ...

    def audit_history(self, memory_id: str, *, limit: int = 100) -> list[dict[str, Any]]: ...

    def close(self) -> None: ...
