THRESHOLDS = {
    "MICROCOMPACT_UTILIZATION": 0.50,
    "AUTOCOMPACT_UTILIZATION": 0.85,
    "BLOCKED_UTILIZATION": 0.95,
}
SNIP_COMPACT_THRESHOLD = 0.70
SNIP_TARGET_USAGE = 0.60
SNIP_MIN_MESSAGES_TO_REMOVE = 6
SNIP_KEEP_RECENT_MESSAGES = 12
SNIP_MIN_TOKENS_TO_FREE = 2_000
CONTEXT_COLLAPSE_UTILIZATION = 0.75
CONTEXT_COLLAPSE_TARGET_USAGE = 0.65
CONTEXT_COLLAPSE_KEEP_RECENT_MESSAGES = 12
CONTEXT_COLLAPSE_MIN_TOKENS_TO_SAVE = 2_000
CONTEXT_COLLAPSE_MAX_SPANS_PER_PASS = 2
CONTEXT_COLLAPSE_MAX_FAILURES = 3
RETENTION = {
    "KEEP_RECENT_TOOL_RESULTS": 3,
    "MIN_KEEP_MESSAGES": 6,
    "MIN_KEEP_TOKENS": 10_000,
    "MAX_KEEP_TOKENS": 40_000,
}
LIMITS = {
    "MAX_AUTOCOMPACT_FAILURES": 3,
    "SUMMARY_MAX_OUTPUT_TOKENS": 4096,
    "PTL_MAX_RETRIES": 2,
    "MIN_EFFECTIVE_INPUT_FOR_AUTOCOMPACT": 20_000,
}
